[package]
name = "encryption_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
rocket = { version = "0.5.0-rc.4", features = ["tls"] }
jsonwebtoken = "9.2.0"
bs58 = "0.5.0"
serde_with = "3.4.0"
blake2 = "0.10.6"
rocket-multipart-form-data = "0.10.7"
hmac = "0.12.1"
[dependencies.uuid]
version = "1.6.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]